# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.4 on 2016-03-10 01:45
=======
# Generated by Django 1.9.4 on 2016-03-10 01:43
>>>>>>> isra/dev
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(default=0)),
<<<<<<< HEAD
                ('tipo', models.CharField(choices=[(b'kg', b'kilogramos'), (b'litros', b'litros'), (b'cajas', b'cajas'), (b'piezas', b'piezas'), (b'paquetes', b'paquetes')], max_length=50)),
=======
                ('tipo', models.CharField(choices=[('kilogramos', 'kilogramos'), ('litros', 'litros'), ('cajas', 'cajas'), ('piezas', 'piezas'), ('paquete', 'paquete')], max_length=50)),
>>>>>>> isra/dev
                ('precio', models.FloatField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(default=0)),
<<<<<<< HEAD
                ('tipo', models.CharField(choices=[(b'kg', b'kilogramos'), (b'litros', b'litros'), (b'cajas', b'cajas'), (b'piezas', b'piezas'), (b'paquetes', b'paquetes')], max_length=50)),
=======
                ('tipo', models.CharField(choices=[('kilogramos', 'kilogramos'), ('litros', 'litros'), ('cajas', 'cajas'), ('piezas', 'piezas'), ('paquete', 'paquete')], max_length=50)),
>>>>>>> isra/dev
                ('precio', models.FloatField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
<<<<<<< HEAD
                'verbose_name_plural': 'Proveedors',
=======
                'verbose_name_plural': 'Proveedores',
>>>>>>> isra/dev
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Proveedor'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Proveedor'),
        ),
    ]
